version: '3.5'

services:
  
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example
    container_name: postgres_db
  redis:
    image: redis
    ports:
      - 6379:6379
  frontend:
    image: node-frontend
    ports:
      - 5000:5000
    environment:
      - API_URL=http://localhost:8000
  backend:
    image: node-backend
    ports:
      - 8000:8000
    environment:
      - FRONT_URL=http://localhost:5000
      - REDIS=redis
      - REDIS_PORT=6379
      - DB_USERNAME=postgres
      - DB_PASSWORD=example
      - DB_HOST=db
    depends_on:
      - db
